/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maze;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

class MazeFactoryTest {
    @Test
    public void testZeroDimensions() {
        assertThrows(IllegalArgumentException.class, () -> MazeFactory.makeMaze(0, 0));
        assertThrows(IllegalArgumentException.class, () -> MazeFactory.makeMaze(0, 10));
        assertThrows(IllegalArgumentException.class, () -> MazeFactory.makeMaze(10, 0));
    }

    @Test
    public void testNegativeDimensions() {
        assertThrows(IllegalArgumentException.class, () -> MazeFactory.makeMaze(10, -10));
        assertThrows(IllegalArgumentException.class, () -> MazeFactory.makeMaze(-10, 10));
    }

    @Test
    public void testSimpleMaze() {
        Maze maze = MazeFactory.makeMaze(10, 10);
        assertEquals(10, maze.getHeight());
        assertEquals(10, maze.getWidth());
    }
}
