/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maze;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNull;

class MazeFactoryTest {
    @Test
    public void testZeroDimensions() {
        assertNull(MazeFactory.make(0, 0));
        assertNull(MazeFactory.make(0, 10));
        assertNull(MazeFactory.make(10, 0));
    }

    @Test
    public void testNegativeDimensions() {
        assertNull(MazeFactory.make(10, -10));
        assertNull(MazeFactory.make(-10, 10));
    }
}
