/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maze;

public final class MazeFactory {
    public static Maze make(int width, int height) {
        return null;
    }
}
